### PR TITLE
add class to instantiate correct class on deserialization of items

### LINKED ISSUE #18: Content is lost when deserializing offer
Hi

First : thanks for your work, very useful to deal with Allegro.

I have encountered a bug when working with offer where description is defined.
Calling getOfferUsingGET on UsersOfferInformationApi class.

On raw API reply description is ok
```json
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<h1>A description</h1>"
          }
        ]
      }
    ]
  },
```

But when deseriazing items model is hardcoded to parent ($openApiTypes) which does not handle content (only type) so content is lost

```php
//vendor/coffeedesk/allegro-api-client-php/src/Model/DescriptionSection.php
    protected static $openAPITypes = [
        'items' => '\AllegroApi\Model\DescriptionSectionItem[]'
    ];
```

Instead child model shoud be used 

- vendor/coffeedesk/allegro-api-client-php/src/Model/DescriptionSectionItemText.php
- vendor/coffeedesk/allegro-api-client-php/src/Model/DescriptionSectionItemImage.php

Regards

### PR DESCRIPTION
**Pull request by lwillems**
Fix #18 

Will force code to instantiance TEXT or IMAGE class with discriminator, thoses classes inherit the right model.

```
//vendor/coffeedesk/allegro-api-client-php/src/ObjectSerializer.php:330
            if (!empty($discriminator) && isset($data->{$discriminator}) && is_string($data->{$discriminator})) {
                $subclass = '\AllegroApi\Model\\' . $data->{$discriminator};
                if (is_subclass_of($subclass, $class)) {
                    $class = $subclass;
                }
            }
```

Regards

### CODE REVIEW

**Review by Arkowsky — APPROVED** [review]

**Comment by lwillems** [comment]
@Arkowsky thx for approval, when did you plan to merge ? so i can remove my fork from my composer.json :-)

**Comment by numerogeek** [comment]
@Arkowsky Hi ! Could you please release a new version of this package including this commit ? Thx !

**Comment by Arkowsky** [comment]
Hi @numerogeek , done.

**Comment by numerogeek** [comment]
Thanks !

**Pull request merged**
